In [2]:
import pandas as pd
mydataset={
    "cars": ["BMW","Volve","AuDi"],
    "passings":[3,7,2]

}
myvar=pd.Series(mydataset)
print(myvar)

a=[1,7,2]
myvar=pd.Series(a)
print(myvar[0])

#label in padas
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a,index=["x","y","z"])

print(myvar["y"])

#Using Index in pandas
calories={"day1":420,"day2":385,"day3":500}
myvar=pd.Series(calories,index=["day1","day2"])

print(myvar)

data={
    "calories":[420,550,700],
    "duration":[50,40,4]

}
myvar=pd.DataFrame(data)
print(myvar)

cars        [BMW, Volve, AuDi]
passings             [3, 7, 2]
dtype: object
1
7
day1    420
day2    385
dtype: int64
   calories  duration
0       420        50
1       550        40
2       700         4

In [3]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
data = {
    "Name": [ "sai", "balu", "lilly", "sweety","dolly", "puri"],
    "Age":[30,40,50,60,70,80],
    "City" : ["New york", "London", "paris", "Tokyo", "Berlin","Sydney"],
    "Salary": [5000,6000,7000, 8000,9000,10000]

}
df =pd.DataFrame(data)
df

     Name  Age      City  Salary
0     sai   30  New york    5000
1    balu   40    London    6000
2   lilly   50     paris    7000
3  sweety   60     Tokyo    8000
4   dolly   70    Berlin    9000
5    puri   80    Sydney   10000

In [9]:
df.head() #prints first 5 rows of the data

     Name  Age      City  Salary
0     sai   30  New york    5000
1    balu   40    London    6000
2   lilly   50     paris    7000
3  sweety   60     Tokyo    8000
4   dolly   70    Berlin    9000

In [10]:
df.tail() #prints last 5 roes of the data

     Name  Age    City  Salary
1    balu   40  London    6000
2   lilly   50   paris    7000
3  sweety   60   Tokyo    8000
4   dolly   70  Berlin    9000
5    puri   80  Sydney   10000

In [11]:
df.shape # prints rows and coloums

(6, 4)

In [13]:
df.info() #prints all detals like rows,coloums,memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
 3   Salary  6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [15]:
df.describe()

             Age        Salary
count   6.000000      6.000000
mean   55.000000   7500.000000
std    18.708287   1870.828693
min    30.000000   5000.000000
25%    42.500000   6250.000000
50%    55.000000   7500.000000
75%    67.500000   8750.000000
max    80.000000  10000.000000

In [16]:
from google.colab import files
uploaded=files.upload()

Saving house.csv to house.csv

In [19]:
import pandas as pd
df=pd.read_csv("house.csv")
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0
1    -122.22     37.86                  21         7099          1106.0
2    -122.24     37.85                  52         1467           190.0
3    -122.25     37.85                  52         1274           235.0
4    -122.25     37.85                  52         1627           280.0

   population  households  median_income  median_house_value ocean_proximity
0         322         126         8.3252              452600        NEAR BAY
1        2401        1138         8.3014              358500        NEAR BAY
2         496         177         7.2574              352100        NEAR BAY
3         558         219         5.6431              341300        NEAR BAY
4         565         259         3.8462              342200        NEAR BAY

In [20]:
import os
print(os.listdir())

['.config', 'house.csv', 'sample_data']

In [24]:
print("Average popuation", df["population"].mean())

Average popuation 1425.4767441860465

In [25]:
df[df['households']>250]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY
6,-122.25,37.84,52,2535,489.0,1094,514,3.6591,299200,NEAR BAY
7,-122.25,37.84,52,3104,687.0,1157,647,3.1200,241400,NEAR BAY
8,-122.26,37.84,42,2555,665.0,1206,595,2.0804,226700,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20634,-121.56,39.27,28,2332,395.0,1041,344,3.7125,116800,INLAND
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,INLAND